#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase0
rm -rf boundaries fieldMeasurements constant/polyMesh/ 
rm -rf ./{[1-9]*,-[1-9]*,*.xml,ParaView*,paraFoam*,*.foam} > /dev/null 2>&1

# ----------------------------------------------------------------- end-of-file
