#!/bin/bash

cd "${0%/*}" || exit  # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions  # Tutorial run functions
#------------------------------------------------------------------------------

str1='/*--------------------------------*- C++ -*----------------------------------*\'
str7='/*---------------------------------------------------------------------------*\'

# Find the first controlDict file and get its header (first 7 lines)
headerFile=$(find $FOAM_TUTORIALS -name "*controlDict*" | head -1)
header=$(head -7 "$headerFile")
echo "Renaming headers to:"
echo "$header"

# Recursively find all files in subdirectories and process them
find . -type f -name "*Dict" -o -name "*Properties" -o -name "*Schemes" -o -name "*Solution" | while read -r file; do
    echo "Processing file: $file"
    # Read the first and seventh lines of the file
    first_line=$(head -1 "$file")
    seventh_line=$(head -7 "$file" | tail -1)
        
    # Remove the first 7 lines and prepend the new header
    tail -n +8 "$file" > "${file}_Temp"
    echo "$header" | cat - "${file}_Temp" > temp && mv temp "${file}_Temp"
    mv "${file}_Temp" "$file"
    #fi
done
