#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication uspInitialise
runApplication `getApplication` &

echo "The simulation is now running, its progress can be viewed by typing 'tail -f log.uspFoam'". &

# ----------------------------------------------------------------- end-of-file
